### ISSUE TITLE
CURLOPT_FOLLOWLOCATION

### ISSUE THREAD

**Issue by bkdotcom** [pdeans/http#3]
`CURLOPT_FOLLOWLOCATION`

> Instead, these options should be provided as part of the request options:

How do I specify `CURLOPT_FOLLOWLOCATION` equivalent via PSR-7 ?

**Comment by pdeans** [comment]
@bkdotcom One way to achieve this would be something similar to the following. Essentially, checking the response status code for a redirect response and issue a new request to the returned location header value, repeating this logic until a non-redirect status code is returned or the redirect limit is hit (if provided).

```php
<?php

use pdeans\Http\Client;

require_once __DIR__ . '/vendor/autoload.php';

$client = new Client();

$max_redirs = 5;
$redir_count = 0;
$url = 'https://example.com';

do {
    $response = $client->get($url);
    $status_code = $response->getStatusCode();
    $url = $response->getHeader('location')[0] ?? '';

    $redir_count++;
} while ($redir_count < $max_redirs && $status_code >= 300 && $status_code <= 399 && $url !== '');
```
